version: '3.8'
services:
  multicamstudio: 
    build:
      context: ./build
      args:
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        CUDA_ARCH_BIN: ${CUDA_ARCH_BIN}
        OPENCV_VERSION: ${OPENCV_VERSION}
        UID: ${UID}
        GID: ${GID}
        CMAKE_VERSION: ${CMAKE_VERSION}
        CPP_OPTIMIZATIONS: ${CPP_OPTIMIZATIONS}
        FLIR_CAMERA_COUNT: ${FLIR_CAMERA_COUNT}
        FLIR_GID: ${FLIR_GID}
    image: my/${TAG1}

    network_mode: host
    command: tail -f /dev/null
    tty: true
    runtime: nvidia
  
    environment:
      DISPLAY: "${DISPLAY}"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      TERM: xterm-256color
      DEBUG_COLORS: "true"
      COLORTERM: truecolor
      CAMERA_SETTINGS_FILE: ${CAMERA_SETTINGS_FILE}
      # SSH_AUTH_SOCK: /ssh-agent # for github dev
    volumes: 
      - ./:/home/docker/workspace
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - $SSH_AUTH_SOCK:/ssh-agent  # Forward SSH socket

    devices:
      - /dev/bus/usb:/dev/bus/usb
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video, compute, utility]